### PR TITLE
[WIP] Quick session loader (starts to implement #454)

### PR DESCRIPTION
**Pull request by alexwhitman**
Thought I'd put up some work in progress. just to check that I'm on the right lines.  The first commit implements the recent session file tracking.  The second commit starts the UI.

If you save a few session files and then hit `Ctrl+Alt+p` the UI will pop up.

Lots of things left to do:
- [x] Filter list when entering text into the search box
- [x] Open session file when hitting Enter in the list
- [x] Focus main window when hitting Escape in the search box
- [x] Handle removing entries from the recent files list when hitting Delete on a focus list box entry
- [x] Make the thing look a lot nicer
- [ ] Other tweaks and fixes I haven't thought about

Any guidance or contributions greatly welcome. :smile:

### CODE REVIEW

**Comment by gnunn1** [comment]
I had a quick look at the code and ran it locally, I think you are on the right path but as you correctly noted there is quite a bit of work to do. A couple of comments as follows:

a. It doesn't close automatically when you click outside of it
b. You'll need to update the.ui file with the new shortcut at some point
c. Should we be keeping track of the session name as well and searching by that rather then filename?

**Comment by alexwhitman** [comment]
I've pushed another commit which handles opening a session file and removing entries from the list.

> a. It doesn't close automatically when you click outside of it

Yes, there's a load of focus related issues which need to be sorted out, at this point I'm not entirely sure what I'm missing but I haven't really looked at it yet.

> b. You'll need to update the.ui file with the new shortcut at some point

That was already done in the second commit.

> c. Should we be keeping track of the session name as well and searching by that rather then filename?

Do-able, although I'm not sure how often sessions get renamed.  I have quite a few session files but I haven't changed them and they all have the name "Default".

In thinking about how to filter the list box when entering search terms into the search box, it seems as though `ListBox::setFilterFunc` would do what I want but the signature for that is
```
void setFilterFunc (GtkListBoxFilterFunc filterFunc, void* userData, GDestroyNotify destroy); 
```
and I can't find any useful information on how to use it within GTKD, particularly the `GtkListBoxFilterFunc`.

**Comment by gnunn1** [comment]
The filterfunc that you set is declared as:

extern(C) int function(gtkc.gtktypes.GtkListBoxRow*, void*) filterFunc

So it looks pretty straight-forward, going by the docs it looks like it would be called for each row and I assume you would return a 0/1 to indicate whether the row should be shown or not.

BTW, I ideally recommend building the ddox version of the GtkD documentation locally, it's light years better then the on-line docs and makes understanding GtkD mich easier. If you need any help with ddox just ping me off-line (gerald dot b dot nunn at gmail dot com).

**Comment by alexwhitman** [comment]
This might be a stupid question but what's the D method of writing a function to implement a GtkListBoxFilterFunc?

**Comment by gnunn1** [comment]
My C-foo is weak, but I think it would be something like (assuming it's in a class not a standalone function otherwise remove the static)

extern (C) static int filterCallback((gtkc.gtktypes.GtkListBoxRow* prow, void* userData) {
   ListBoxRow row = ObjectG.getDObject!(ListBoxRow)(prow);
   if (row !is null) {

   }
}

**Comment by alexwhitman** [comment]
Managed to figure out the filtering bit after a while and many casts between data types.

Right now it only does a basic string in string filter rather than a fuzzy search, I'm going to have to think of the best way of implementing that or seeing if there's an existing library to leverage.

**Comment by alexwhitman** [comment]
Which bit of code is responsible for hiding the sidebar when it loses focus?  I think I've fixed all of the other focus issues but can't figure out this one.  Maybe I've been staring at the code for too long.

**Comment by gnunn1** [comment]
It's this code in sidebar.d, not very intuitive but since it grabs the mouse any mouse click events outside of the sidebar trigger a close via passing a null to the sessionselected event.

```
    bool onButtonPress(Event event, Widget w) {
        trace("** Sidebar button press");
        //If button press happened outside of sidebar close it
        if (event.getWindow() !is null && lbSessions.getWindow() !is null) { 
            if (event.getWindow().getWindowStruct() != getWindow().getWindowStruct() && event.getWindow().getWindowStruct() != lbSessions.getWindow().getWindowStruct()) {
                notifySessionSelected(null);
            }
        }
        return false;
    }
```

**Comment by alexwhitman** [comment]
Thanks, I've had a quick look at that at while I can get focus grabbed, the onButtonPress function doesn't get called.  I'll have another look later.

I think I've fixed a lot of the other things, it just needs to look better than it currently does but I'm no UI designer.

**Comment by alexwhitman** [comment]
I think this is almost there.

Right now the search is only a simple string in string search but I'm planning on porting https://github.com/jeancroy/fuzzaldrin-plus/ to D and creating a package when I get some more time but for now the simple search works.

It still doesn't look great, could probably do with someone with a flair for design to take a look.  The images used at the moment are temporary.

@gnunn1 Feel free to give any feedback or suggestions.

**Comment by alexwhitman** [comment]
I think this is as far as I'll be able to get it, at least for the next few weeks.  Known issues remaining are

- [ ] Needs visual go over.
- [ ] The ListBox should probably be in a ScrolledWindow but I've tried a few things I can't get the ScrolledWindow to have any height unless it's hard coded (which is then probably too big when there are only a few rows).  Hopefully fixable as part of visual updates.
- [ ] Doesn't have the fuzzy string search, just a case insensitive string in string search but it works for now and might be enough.  Can wait for feedback on this one.

**Comment by gnunn1** [comment]
With regards to the ScrolledWindow, I usually just call setSizeRequest to set a reasonable default height for it. Here's an example from the password manager dialog I recently added:

```
        ScrolledWindow sw = new ScrolledWindow(tv);
        sw.setShadowType(ShadowType.ETCHED_IN);
        sw.setPolicy(PolicyType.NEVER, PolicyType.AUTOMATIC);
        sw.setHexpand(true);
        sw.setVexpand(true);
        sw.setSizeRequest(-1, 200);
```

I'll merge this during the weekend and do any cleanup needed for the UI.

**Comment by alexwhitman** [comment]
I've added the list box into a ScrolledWindow with a default height which works.  I've tried to make it a bit cleaner by making the height depend on the height of the ListBox but calling `getHeight()` on the ListBox always returns `-1` even when the widget is visible.

**Pull request merged**
