### PR TITLE
Add action shortcut "New Terminal" and Update Russian localization

### LINKED ISSUE #369: Do not add an icon to the dock Plank

### PR DESCRIPTION
**Pull request by igor-dyatlov**

### CODE REVIEW

**Comment by gnunn1** [comment]
Thanks, I'm probably not going to get a chance to look at this and merge it until tomorrow night as I'm travelling today.

**Comment by gnunn1** [comment]
I need to understand what this is fixing in #369 before I can merge it as per the comment I left there, hopefully the OP will respond.

**Comment by gnunn1** [comment]
And this has conflicts that need resolving first as well.

**Comment by igor-dyatlov** [comment]
Closed

**Pull request closed without merging**
