### PR TITLE
Fix build on 32bit architectures

### LINKED ISSUE #110: Error compiling
I tried to compile terminix using dmd  v2.070.0 and got this error (Ubuntu 14.04.03, x86);

source/gx/terminix/application.d(110,49): Error: function glib.Variant.Variant.getString (out uint length) is not callable using argument types (ulong)
/usr/include/dmd/phobos/std/algorithm/mutation.d(1697,32): Error: template std.range.primitives.popFrontExactly cannot deduce function from argument types !()(AppWindow[], long), candidates are:
/usr/include/dmd/phobos/std/range/primitives.d(1798,6):        std.range.primitives.popFrontExactly(Range)(ref Range r, size_t n) if (isInputRange!Range)
/usr/include/dmd/phobos/std/algorithm/mutation.d(1698,32): Error: template std.range.primitives.popFrontExactly cannot deduce function from argument types !()(AppWindow[], long), candidates are:
/usr/include/dmd/phobos/std/range/primitives.d(1798,6):        std.range.primitives.popFrontExactly(Range)(ref Range r, size_t n) if (isInputRange!Range)
/usr/include/dmd/phobos/std/algorithm/mutation.d(1699,19): Error: cannot implicitly convert expression (from) of type long to uint
source/gx/util/array.d(22,37): Error: template instance std.algorithm.mutation.remove!(cast(SwapStrategy)2, AppWindow[], long) error instantiating
source/gx/terminix/application.d(344,29):        instantiated from here: remove!(AppWindow)
/usr/include/dmd/phobos/std/algorithm/mutation.d(1697,32): Error: template std.range.primitives.popFrontExactly cannot deduce function from argument types !()(ProfileWindow[], long), candidates are:
/usr/include/dmd/phobos/std/range/primitives.d(1798,6):        std.range.primitives.popFrontExactly(Range)(ref Range r, size_t n) if (isInputRange!Range)
/usr/include/dmd/phobos/std/algorithm/mutation.d(1698,32): Error: template std.range.primitives.popFrontExactly cannot deduce function from argument types !()(ProfileWindow[], long), candidates are:
/usr/include/dmd/phobos/std/range/primitives.d(1798,6):        std.range.primitives.popFrontExactly(Range)(ref Range r, size_t n) if (isInputRange!Range)
/usr/include/dmd/phobos/std/algorithm/mutation.d(1699,19): Error: cannot implicitly convert expression (from) of type long to uint
source/gx/util/array.d(22,37): Error: template instance std.algorithm.mutation.remove!(cast(SwapStrategy)2, ProfileWindow[], long) error instantiating
source/gx/terminix/application.d(355,29):        instantiated from here: remove!(ProfileWindow)
/usr/include/dmd/phobos/std/algorithm/mutation.d(1697,32): Error: template std.range.primitives.popFrontExactly cannot deduce function from argument types !()(bool delegate(ActionType)[], long), candidates are:
/usr/include/dmd/phobos/std/range/primitives.d(1798,6):        std.range.primitives.popFrontExactly(Range)(ref Range r, size_t n) if (isInputRange!Range)
/usr/include/dmd/phobos/std/algorithm/mutation.d(1698,32): Error: template std.range.primitives.popFrontExactly cannot deduce function from argument types !()(bool delegate(ActionType)[], long), candidates are:
/usr/include/dmd/phobos/std/range/primitives.d(1798,6):        std.range.primitives.popFrontExactly(Range)(ref Range r, size_t n) if (isInputRange!Range)
/usr/include/dmd/phobos/std/algorithm/mutation.d(1699,19): Error: cannot implicitly convert expression (from) of type long to uint
source/gx/util/array.d(22,37): Error: template instance std.algorithm.mutation.remove!(cast(SwapStrategy)2, bool delegate(ActionType)[], long) error instantiating
source/gx/terminix/common.d(44,29):        instantiated from here: remove!(bool delegate(ActionType))
/usr/include/dmd/phobos/std/algorithm/mutation.d(1697,32): Error: template std.range.primitives.popFrontExactly cannot deduce function from argument types !()(void delegate(string, string, string, string)[], long), candidates are:
/usr/include/dmd/phobos/std/range/primitives.d(1798,6):        std.range.primitives.popFrontExactly(Range)(ref Range r, size_t n) if (isInputRange!Range)
/usr/include/dmd/phobos/std/algorithm/mutation.d(1698,32): Error: template std.range.primitives.popFrontExactly cannot deduce function from argument types !()(void delegate(string, string, string, string)[], long), candidates are:
/usr/include/dmd/phobos/std/range/primitives.d(1798,6):        std.range.primitives.popFrontExactly(Range)(ref Range r, size_t n) if (isInputRange!Range)
/usr/include/dmd/phobos/std/algorithm/mutation.d(1699,19): Error: cannot implicitly convert expression (from) of type long to uint
source/gx/util/array.d(22,37): Error: template instance std.algorithm.mutation.remove!(cast(SwapStrategy)2, void delegate(string, string, string, string)[], long) error instantiating
source/gx/terminix/common.d(83,29):        instantiated from here: remove!(void delegate(string, string, string, string))
source/gx/terminix/cmdparams.d(57,35): Error: function glib.Variant.Variant.getString (out uint length) is not callable using argument types (ulong)
source/gx/terminix/cmdparams.d(80,26): Error: cannot implicitly convert expression (i) of type ulong to uint
source/gx/terminix/cmdparams.d(81,38): Error: cannot implicitly convert expression (i) of type ulong to uint
dmd failed with exit code 1.

### PR DESCRIPTION
**Pull request by ximion**
This allows building Terminix on x86 and various ARM architectures.

I just verified that the build works properly, there might be issues at runtime that this patch doesn't cover (although it's not likely).

This should also resolve #110 properly.

### CODE REVIEW

**Comment by gnunn1** [comment]
Thanks for the PR, as per the FAQ I'm quite happy to take PR requests that fix 32 bit issues. However just to re-iterate I'm not officially supporting 32 bit builds in the sense that I'm not building or testing in a 32 bit environment, nor am I supporting bugs on 32 bit that can't be replicated in a 64 bit environment.

**Comment by ximion** [comment]
You could have the CI test 32bit for you (requires a bit of work on the scripts though).
Accepting patches is completely fine though, nobody expects you to do work on things you don't use :-)
And given that D is actually quite well-suited for cross-platform development, I don't see a reason why there should be bugs on other architectures where Terminix itself is to blame, it would be more likely that such issues lie in the toolchain in these cases.
Anyway, we will have Debian people find potential problems while the package is in unstable/testing :-)

**Comment by gnunn1** [comment]
Good idea on CI unfortunately I don't think Travis supports 32 bit, see here:

https://github.com/travis-ci/travis-ci/issues/986

Without that it's not possible for me to guarantee that the code can be built by the 32 bit version of the D compilers, I just don't have time to deal with that aspect of things. Having said that, I'll do my best to remember to use size_t where appropriate :)

**Comment by ximion** [comment]
Well, you can spawn a Docker container or chroot inside Travis to build for i686 ;-)
I did that hack once, today I am mostly building inside Docker environments inside Travis, because the toolchain in Travis and the dependencies in there is quite ancient.
But yeah, it's annoying ^^

**Pull request merged**
