### PR TITLE
using env so that it will run on more systems

### PR DESCRIPTION
**Pull request by jonorthwash**

### CODE REVIEW

**Comment by gnunn1** [comment]
I'm curious, are there any Linux distros that can't work with that shebang, I always thought the environment thing was mostly useful when trying to use the same script for other nix's like BSD?

**Comment by jonorthwash** [comment]
Didn't work on my system: for me it's `/bin/sh`.  Using `env` is safer, pretty sure.

**Comment by gnunn1** [comment]
What distro are you using?

**Comment by jonorthwash** [comment]
Current debian unstable.

**Pull request merged**
